name: CI/CD (simple)

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t ghcr.io/larsappel/dockerdemoapp:latest
          docker push ghcr.io/larsappel/dockerdemoapp:latest

  deploy_to_vm:
    needs: build_and_push
    runs-on: self-hosted

    steps:
      - name: Stop and remove existing container
        run: sudo docker stop dockerdemoapp || true && sudo docker rm dockerdemoapp || true

      - name: Start the new container
        run: sudo docker run -d -p 80:8080 --name dockerdemoapp ghcr.io/larsappel/dockerdemoapp:latest

  deploy_to_azure_container_apps:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name dockerdemoapp \
            --resource-group DockerDemoRG \
            --image ghcr.io/larsappel/dockerdemoapp:latest
      